name: warranty
version: 1.0.0+1
publish_to: none
description: PPSW Warranty.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  dio: ^5.3.0
  get: 4.6.5
  talker_flutter: ^3.1.7
  data_table_2: ^2.5.4
  image_picker: ^0.8.7+5
  fl_chart: ^0.63.0
  connectivity_plus: ^4.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

assets:
  - web/assets/
